In [1]:
import numpy as np

In [2]:
x = np.array([2,4,6,8,10,12,14,16,18,20])

In [3]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
x = ['hello',12,10.5]

In [5]:
y = np.array(x)

In [6]:
y

array(['hello', '12', '10.5'], dtype='<U5')

In [7]:
np.array([1,2,4,65,6,10.55])

array([ 1.  ,  2.  ,  4.  , 65.  ,  6.  , 10.55])

In [8]:
np.array([1,2,4,65,6,10.55,True])

array([ 1.  ,  2.  ,  4.  , 65.  ,  6.  , 10.55,  1.  ])

In [9]:
np.array([1,2,4,65,6,10.55,True,'Hello'])

array(['1', '2', '4', '65', '6', '10.55', 'True', 'Hello'], dtype='<U32')

In [10]:
x1 = np.array([i for i in range(2,21,2)])

In [11]:
x1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
x1.shape

(10,)

In [13]:
x1.ndim

1

In [15]:
print(x1[0:5])

[ 2  4  6  8 10]


In [16]:
x1 = np.array([[10,21,34,44],[1,2,5,7],[24,34,56,78],[11,14,16,19]])

In [17]:
x1

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7],
       [24, 34, 56, 78],
       [11, 14, 16, 19]])

In [18]:
x1[0]

array([10, 21, 34, 44])

In [19]:
x1.shape

(4, 4)

In [20]:
x1.ndim

2

In [21]:
x1[0][0]

10

In [22]:
x1[0:2]

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7]])

In [26]:
# x1[row,col]
x1[0:2,0:2]

array([[10, 21],
       [ 1,  2]])

In [27]:
x1

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7],
       [24, 34, 56, 78],
       [11, 14, 16, 19]])

In [29]:
x2 = x1.reshape(2,8)

In [30]:
x2

array([[10, 21, 34, 44,  1,  2,  5,  7],
       [24, 34, 56, 78, 11, 14, 16, 19]])

In [31]:
# Transpose Matrix
x3 = x2.T

In [32]:
x3

array([[10, 24],
       [21, 34],
       [34, 56],
       [44, 78],
       [ 1, 11],
       [ 2, 14],
       [ 5, 16],
       [ 7, 19]])

In [33]:
x3.flatten()

array([10, 24, 21, 34, 34, 56, 44, 78,  1, 11,  2, 14,  5, 16,  7, 19])

# Ways to create array in numpy

In [34]:
# First Method
np.array([3,5,6,7,8,4,21,56,77])

array([ 3,  5,  6,  7,  8,  4, 21, 56, 77])

In [35]:
# Second Method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [38]:
# Third Method
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Fourth Method - identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
# Fifth Method - linear space
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [43]:
np.linspace(1,10,retstep=True,num=15,)

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 0.6428571428571429)