In [1]:
import numpy as np

In [2]:
x = np.array([2,4,6,8,10,12,14,16,18,20])

In [3]:
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
x = ['hello',12,10.5]

In [5]:
y = np.array(x)

In [6]:
y

array(['hello', '12', '10.5'], dtype='<U5')

In [7]:
np.array([1,2,4,65,6,10.55])

array([ 1.  ,  2.  ,  4.  , 65.  ,  6.  , 10.55])

In [8]:
np.array([1,2,4,65,6,10.55,True])

array([ 1.  ,  2.  ,  4.  , 65.  ,  6.  , 10.55,  1.  ])

In [9]:
np.array([1,2,4,65,6,10.55,True,'Hello'])

array(['1', '2', '4', '65', '6', '10.55', 'True', 'Hello'], dtype='<U32')

In [10]:
x1 = np.array([i for i in range(2,21,2)])

In [11]:
x1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
x1.shape

(10,)

In [13]:
x1.ndim

1

In [14]:
print(x1[0:5])

[ 2  4  6  8 10]


In [15]:
x1 = np.array([[10,21,34,44],[1,2,5,7],[24,34,56,78],[11,14,16,19]])

In [16]:
x1

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7],
       [24, 34, 56, 78],
       [11, 14, 16, 19]])

In [17]:
x1[0]

array([10, 21, 34, 44])

In [18]:
x1.shape

(4, 4)

In [19]:
x1.ndim

2

In [20]:
x1[0][0]

10

In [21]:
x1[0:2]

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7]])

In [22]:
# x1[row,col]
x1[0:2,0:2]

array([[10, 21],
       [ 1,  2]])

In [23]:
x1

array([[10, 21, 34, 44],
       [ 1,  2,  5,  7],
       [24, 34, 56, 78],
       [11, 14, 16, 19]])

In [24]:
x2 = x1.reshape(2,8)

In [25]:
x2

array([[10, 21, 34, 44,  1,  2,  5,  7],
       [24, 34, 56, 78, 11, 14, 16, 19]])

In [26]:
# Transpose Matrix
x3 = x2.T

In [27]:
x3

array([[10, 24],
       [21, 34],
       [34, 56],
       [44, 78],
       [ 1, 11],
       [ 2, 14],
       [ 5, 16],
       [ 7, 19]])

In [28]:
x3.flatten()

array([10, 24, 21, 34, 34, 56, 44, 78,  1, 11,  2, 14,  5, 16,  7, 19])

# Ways to create array in numpy

In [29]:
# First Method
np.array([3,5,6,7,8,4,21,56,77])

array([ 3,  5,  6,  7,  8,  4, 21, 56, 77])

In [30]:
# Second Method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
# Third Method
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# Fourth Method - identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# Fifth Method - linear space
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [36]:
np.linspace(1,10,retstep=True,num=15,)

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 0.6428571428571429)

In [37]:
# Sixth Method
np.random.random()

0.635476138782198

In [38]:
np.random.random(size=(2,2))

array([[0.18173306, 0.44785346],
       [0.04657984, 0.89037338]])

In [42]:
# will return 10 random numbers b/w 5 and 50
np.random.randint(5,50,10)

array([43,  5,  6, 38, 47, 35,  9, 10, 25, 31])

In [45]:
np.random.randn(5,5)

array([[ 2.35049047, -0.0440792 ,  2.6837194 , -2.28777966, -1.7705686 ],
       [ 0.21706037,  0.85167683, -1.87840738,  0.29208973, -1.55570136],
       [ 0.0606469 ,  0.20826393, -0.67641559, -0.95865489, -0.09228361],
       [-1.49288936,  1.06590702,  1.42225393,  0.49230007,  0.88966732],
       [-0.35521563,  1.3518544 , -1.51251233,  0.34948619, -0.43105642]])

In [66]:
np.random.seed(0)

In [67]:
np.random.randint(5,50,6)

array([49,  5,  8,  8, 44, 14])

In [86]:
#Seventh Method
x = np.arange(1,20,3)
print(x)

[ 1  4  7 10 13 16 19]


# Numpy Methods

In [77]:
arr = np.random.randint(100,1000,100)

In [78]:
arr.min()

111

In [79]:
arr.max()

989

In [80]:
arr.argmin()

46

In [81]:
arr[50]

132

In [82]:
arr.argmax()

90

In [83]:
arr.argsort()

array([46, 74, 23, 98, 50, 41, 38, 44, 39, 49, 43, 67,  4, 27, 97, 30, 52,
       25, 87, 33, 96, 95,  1, 55, 80, 51, 58,  5, 17, 34, 68, 79,  7, 85,
       70, 54, 63, 62, 10, 72, 48, 81, 73, 16, 20, 57, 26, 22, 18, 13, 77,
       36, 59,  3, 78, 89, 99, 60, 19, 66, 94, 15, 56, 21, 35, 28,  0, 61,
       31, 88,  6, 75, 14, 91, 64,  2,  9, 93, 24, 40, 29, 32, 86, 47, 65,
       42, 37, 83, 53, 11, 82, 76, 92, 12, 84, 45, 69, 71,  8, 90],
      dtype=int64)

In [85]:
arr.mean()

527.99